vulsio/vulsctl

install-host.sh

Hello,
I have developed an automated vuls installation script that can be installed in an HOST environment.
Currently, only Ubuntu OS is supported. (I'll keep updating.)
Thanks.

Add host Install Script

---

install-host.sh

The defined color are not displayed when the `-e` argument on the `echo` command is not specified.
So I've added the required argument to solve the issue.

Fixed color display / RHEL + CentOS support + Fixes

---

config.toml.template

Related to. https://github.com/future-architect/vuls/pull/1005

add sshConfigPath in template

---

install-host.sh

Hello,
I added Pop!_OS  os support to the host install script.
"Pop!_OS" is an OS based on Ubuntu.
So there is only a small change.
test log
```
roo@pop-os:~/Desktop/vulsctl$ sudo ./install-host.sh 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:9.3.0-1ubuntu2).
gcc set to manually installed.
git is already the newest version (1:2.25.1-1ubuntu3).
git set to manually installed.
make is already the newest version (4.2.1-1.2).
make set to manually installed.
wget is already the newest version (1.20.3-1ubuntu1).
wget set to manually installed.
The following additional packages will be installed:
libsqlite0 libsqlite3-0 sqlite3
Suggested packages:
sqlite-doc sqlite3-doc
The following NEW packages will be …
```

Add Pop!_OS Install Script

---

config.toml.template
msfdb.sh
update-all.sh

ref: https://github.com/future-architect/vuls/pull/1011

add go-msfdb script

---

install-host.sh

Hello,
There was a problem downloading golang.
I solved this problem, and deleted the duplicate code (centos).
Thanks.

fix golang download

---

.gitignore
docker/gost.sh
docker/update-all-redis.sh
docker/update-all.sh
install-host/gost.sh
install-host/update-all.sh

gost@v0.2.0 has been released. 
In v0.2.0, batch insert and Ubuntu support have been added.
https://github.com/knqyf263/gost/releases/tag/v0.2.0

feat(gost): update cmd for gost@v0.2.0

---

docker/oval.sh
install-host/install.sh
install-host/oval.sh
install-host/update-all.sh
install-host/upgrade.sh

refs. https://github.com/kotakanbe/goval-dictionary/pull/137

feat: update the command according to goval-dictionary update

---

docker/msfdb.sh

refs. https://github.com/takuzoo3868/go-msfdb/pull/21

chore: fix path(container: vuls/go-msfdb)

---

docker/gost.sh

refs. https://github.com/knqyf263/gost/pull/71

chore: fix path(container: vuls/gost)

---

docker/server.sh

parameter prevents the server from starting properly

removing unused parameter

---

docker/jvn.sh
docker/nvd.sh
install-host/cvedb.sh
install-host/install.sh
install-host/upgrade.sh

refs. https://github.com/kotakanbe/go-cve-dictionary/pull/193

feat: update the command according to the go-cve-dictionary update

---

docker/exploitdb.sh

refs. https://github.com/vulsio/go-exploitdb/pull/47

[WIP] chore: fix path(container: vuls/go-exploitdb)

---

docker/jvn.sh
docker/nvd.sh
docker/update-all-redis.sh

EROR[08-24|21:24:40] Failed to NewDB. Since SchemaVersion is
incompatible, delete Database and fetch again
Failed to NewDB. Since SchemaVersion is incompatible, delete Database
and fetch again.

fix: Failed to NewDB. Since SchemaVersion is incompatible

---

docker/oval.sh
install-host/oval.sh

refs. https://github.com/kotakanbe/goval-dictionary/pull/149

feat(oval): support debian bullseye

---

docker/jvn.sh
docker/nvd.sh
install-host/cvedb.sh

refs. https://github.com/kotakanbe/go-cve-dictionary/pull/214

feat(go-cve-dictionary): update command

---

install-host/install.sh
install-host/upgrade.sh

Change repository owner to `vulsio`.

chore: change repository owner

---

docker/exploitdb.sh
docker/gost.sh
docker/jvn.sh
docker/msfdb.sh
docker/nvd.sh
docker/oval.sh
docker/update-all-redis.sh
docker/update-all.sh
install-host/cvedb.sh

https://github.com/future-architect/vuls/releases/tag/v0.18.0

fix for Vuls v0.18.0

---

config.toml.template
docker/kev.sh
docker/update-all-redis.sh
docker/update-all.sh
install-host/install.sh
install-host/kev.sh
install-host/update-all.sh
install-host/upgrade.sh

[vulsio/go-kev](https://github.com/vulsio/go-kev) has been implemented to manage the Known Exploited Vulnerabilities Catalog provided by Cybersecurity & Infrastructure Security Agency. script to go-kev is added to vulsctl.

feat: add go-kev

---

docker/oval.sh
docker/update-all-redis.sh
docker/update-all.sh
install-host/install.sh
install-host/oval.sh
install-host/update-all.sh
install-host/upgrade.sh

refs. https://github.com/vulsio/goval-dictionary/pull/196 
Trailing white spaces are automatically removed by editor.

feat(fedora): support fedora

---

docker/exploitdb.sh
install-host/exploitdb.sh

Fetch awesomepoc, githubrepos, inthewild with go-exploitdb.

feat(exploitdb): add fetch datasource

---

docker/oval.sh
install-host/oval.sh

feat(os): add RHEL 9

---

docker/oval.sh
install-host/oval.sh

refs https://github.com/future-architect/vuls/pull/1479

feat(os): add Alpine Linux 3.16

---

docker/exploitdb.sh
install-host/exploitdb.sh

refs. https://github.com/vulsio/go-exploitdb/pull/101

feat(exploitdb): remove awesomepoc

---

docker/jvn.sh

remove-tty-requirement to jvn

---

docker/oval.sh
install-host/oval.sh

refs https://github.com/vulsio/goval-dictionary/pull/289

feat(oval): add amazon and oracle fetch version

---

docker/oval.sh
install-host/oval.sh

refs https://github.com/vulsio/goval-dictionary/pull/199

feat(oval): fetch ubuntu major.minor version

---

install-host/install.sh

Fixes https://github.com/future-architect/vuls/issues/1932
```console
$ docker run --rm -it alpine:3.19 sh
/ # apk add curl
/ # curl -L https://github.com/vulsio/vulsctl/archive/refs/heads/MaineK00n/install-alpine.tar.gz -o vulsctl.tar.gz
/ # mkdir vulsctl
/ # tar -xvf vulsctl.tar.gz -C vulsctl --strip-components 1
/ # vulsctl/install-host/install.sh alpine
...
Done.
```

feat: support alpine in install.sh

---

docker/cvedb.sh
docker/update-all-redis.sh
docker/update-all.sh
install-host/cvedb.sh
install-host/update-all.sh

refs .https://github.com/vulsio/go-cve-dictionary/pull/392

feat(cvedb/mitre): support for fetching mitre
